### ISSUE TITLE
Codec issue

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/cabin-porn#17]
The last fix didn't solve stuff, I think. 

```sh
10:57 ~ 🐕  cabin -r
Traceback (most recent call last):
  File "/usr/local/bin/cabin", line 75, in <module>
    link_str = str(image.get("title"))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 52: ordinal not in range(128)
```

**Comment by shadowhand** [comment]
![grumpybugs](https://cloud.githubusercontent.com/assets/38203/10284407/7a7eb3bc-6b49-11e5-872a-180c9ad9528d.jpg)

**Comment by RichardLitt** [comment]
This. This right there.

**Comment by RichardLitt** [comment]
Luckily, I am an exterminator.

![moushunt](http://piddleville.com/wp-content/uploads/2011/03/mouse_hunt_02.jpg)

**Comment by shadowhand** [comment]
Don't worry I got this...

![gtfo](https://cloud.githubusercontent.com/assets/38203/10298030/49f9b678-6b9f-11e5-8c6f-49cf010b0856.gif)

**Comment by RichardLitt** [comment]
![jj](https://i.imgur.com/v7c1kEZ.gif?noredirect)
