### ISSUE TITLE
 No module named AppKit

### ISSUE THREAD

**Issue by zeke** [RichardLitt/cabin-porn#5]
Howdy,

I'm on OS X Mavericks, and I just installed python with homebrew. Here's what I'm seeing in the cloned repo directory:

```
cabin-porn master » python cabin-porn-it.py
Traceback (most recent call last):
  File "cabin-porn-it.py", line 19, in <module>
    from AppKit import NSWorkspace, NSScreen
ImportError: No module named AppKit

cabin-porn master » pip list               
beautifulsoup4 (4.3.2)
pip (1.5.6)
requests (2.3.0)
setuptools (5.3)
wsgiref (0.1.2)

cabin-porn master » python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print (sys.version)
2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
```

Any ideas?

**Comment by arrowtype** [comment]
I know it's been quite awhile since this thread happened, but I was getting a similar error today, and I solved it by using `python3 -m easy_install pyobjc` in my virtual environment. Cheers!

**Comment by RichardLitt** [comment]
Whoa! Sweet. Maybe worth a PR?

**Comment by arrowtype** [comment]
Ha, sorry, it was actually related to a completely different library I was using. I think it might have been something that got out of line with my macOS system, or my PATH? No entirely sure; just wanted to say thanks.

**Comment by zeke** [comment]
👋 Happy belated five year anniversary to this issue. 🍰

**Comment by RichardLitt** [comment]
:D This is getting to be a pretty old repo. I don't even know if it still works. 💭

**Comment by nitinneo0402** [comment]
hi 
if u guys are still there then i am facing the same issue
i am a newbee on python and trying to use play sound
but it gives the Appkit error on MacOS

**Comment by nitver73** [comment]
i tried the installation they pip install and easy install
but still no luck
can u guys help?

**Comment by nitinneo0402** [comment]
ok it worked
just had to restart python
